[project]
name = "multi-agent-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9.0",
    "beautifulsoup4>=4.12.0",
    "chromadb>=0.5.0",
    "deep-translator>=1.11.4",
    "ffmpeg-python>=0.2.0",
    "fpdf2>=2.7.9",
    "html5lib>=1.1",
    "huggingface-hub>=0.23.0",
    "langchain>=0.2.0",
    "langchain-community>=0.2.0",
    "langchain-core>=0.2.0",
    "langchain-huggingface>=0.0.3",
    "langchain-mistralai>=0.1.0",
    "langchain-openai>=0.1.0",
    "mistralai>=0.4.0",
    "numpy>=1.26.0",
    "openai>=1.30.0",
    "openai-whisper>=20231117",
    "orjson>=3.9.0",
    "pandas>=2.0.0",
    "pydantic>=2.5.0",
    "pydub>=0.25.1",
    "python-dotenv>=1.0.0",
    "reportlab>=4.2.0",
    "requests>=2.32.0",
    "rich>=13.7.0",
    "sentence-transformers>=3.0.0",
    "streamlit>=1.35.0",
    "streamlit-extras>=0.4.0",
    "tavily-python>=0.3.0",
    "tenacity>=8.2.0",
    "tiktoken>=0.7.0",
    "tools>=1.0.27",
    "torch>=2.2.0",
    "torchaudio>=2.2.0",
    "tqdm>=4.66.0",
    "watchdog>=4.0.0",
    "yt-dlp>=2024.4.9",
]
